[global]
developmentMode = false

[server]
headless = true
address = "0.0.0.0"
port = 10000
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 10000

[theme]
base = "light"
primaryColor = "#007AFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[runner]
magicEnabled = true

[mapbox]
token = ""
