services:
  molecular-prediction-suite:
    build: .
    ports:
      - "10000:10000"  # Main launcher app
      - "8501:8501"    # Graph Neural Network app
      - "8502:8502"    # RDKit descriptor app
      - "8503:8503"    # ChemBERTa app
      - "8504:8504"    # Circular fingerprint app
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - STREAMLIT_SERVER_PORT=10000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
